### ISSUE TITLE
screencasts/videos

### ISSUE THREAD

**Issue by aviv** [dobtco/knowledge_base#114]
cf. http://www.soundslice.com/help/

**Comment by ajb** [comment]
I think this would be great to work on. The bulk of the work (in my experience) is in writing and editing the script -- @aviv: would you want to take the lead on researching what we should do a screencast of, and then writing a couple scripts? 

I'm assuming these should be short (1-2 minute) how-tos on completing specific tasks in Screendoor. In my mind, anything that a non-technical user would have trouble figuring out on their own is a good candidate for a how-to screencast.

**Comment by aviv** [comment]
Yeah, sounds great. Here's a few ideas:

- Setting up a basic form using the form-builder.
- Adding "custom" statuses and using them in a workflow.
- Sending a message (+ message presets) to respondents.
- Importing responses.
- Setting up evaluation fields.
- "Collaborative workflow" with statuses, assignment, comments/at-mentions, evaluation.

Maybe it's worth pinging Clay or JG to see if they have suggestions for what how-tos would be most applicable/useful, or maybe Josh has a better idea of what our existing customers are struggling with most?

**Comment by ajb** [comment]
Yeah, those all sound great. I'd start with imports and the formbuilder. /cc @jrubenoff if he has any more feedback

**Comment by jrubenoff** [comment]
FWIW, the original post referred to microvideos intended to make help pages easier to read, not screencasts: https://www.soundslice.com/features/

**Comment by ajb** [comment]
Ah, that's key. I could see both as being useful.

**Comment by jrubenoff** [comment]
This is covered with a few GIFs and text walkthroughs in #229, I think. See [this](https://github.com/dobtco/knowledge_base/blob/revamp/contents/articles/screendoor/images/search_label.gif), for example.

**Comment by ajb** [comment]
Nice, I didn't even notice those when reviewing the PR. Smooth :D

On Thu, Sep 3, 2015 at 2:41 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Closed #114 <https://github.com/dobtco/knowledge_base/issues/114>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/issues/114#event-400411052>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
