### ISSUE TITLE
More consistent image widths

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#124]
Example: http://help.dunked.com/knowledge_base/topics/add-a-new-project

**Comment by ajb** [comment]
I'm in favor of using consistent image widths, along with circles or highlights to point to a specific element on the page. In addition to making the knowledge base layout look better, I think it gives context to a certain screenshot.

Ugly example:

![img](http://take.ms/FTr0c)

We don't have to update all the existing sections at once (that would suck), but maybe there's a good place to start?

**Comment by aviv** [comment]
:+1: Focusing on screenshots that involve smaller UI elements taken out of context (i.e. they'd benefit from better contextualization) and/or articles that contain lots of screenshots would be best.

**Comment by aviv** [comment]
I'm feeling like I could use some busy-work in the next couple days, so I might just knock this out.

**Comment by aviv** [comment]
Moving to PR
