### ISSUE TITLE
Add resources to writing good content

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/knowledge_base#143]
Until we have the time to start writing our own content, we can start adding links to experts.

- Books (Clout, Nicely Said, Elements of Content Strategy)
- http://academy.govloop.com/courses/plain-language/

**Comment by aviv** [comment]
We need to do some thinking about how this is going to fit into the knowledge base's existing structure. "How to write" isn't the same as "how to use Screendoor."

Possible solution: an "additional resources" section.

Related to writing good content is building good forms, which we should probably focus on (and possibly prioritize) if we're going to include resources like this in the knowledge base.

**Comment by ajb** [comment]
:+1: it would be cool to have this kind of stuff in the knowledge base, as long as it doesn't get in the way of people just looking for the "straight steps" on how to do something in Screendoor. I'd even put https://github.com/dobtco/knowledge_base/issues/114 in this category of "additional content".

**Comment by aviv** [comment]
Sounds good, throwing these related issues into a milestone.

**Comment by aviv** [comment]
closing in favor of PR
