### ISSUE TITLE
Add notes about permissions where applicable

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#147]
- "Save as template"
- Where else?

cf https://app.intercom.io/a/apps/6jdp7eoo/inbox/conversation/731118809?nsrc=slack

**Comment by aviv** [comment]
Was this a permissions issue or an account limits issue?

**Comment by ajb** [comment]
Permissions -- they didn't have "manage project templates" checked.

**Comment by aviv** [comment]
Will update the knowledge base, but I'm actually wondering *why* we have this stuff in two different places.

- Screendoor collaborators page:

![](http://take.ms/q4R2H)

- Dashboard user page:

![](http://take.ms/yG8Ow)

**Comment by ajb** [comment]
Site-wide vs project-wide preferences?

**Comment by aviv** [comment]
But doesn't that beg the question: why is `x` (e.g. "manage collaborators") a project-wide preference while `y` (e.g. "manage payments") is site-wide?

**Comment by ajb** [comment]
> But doesn't that beg the question: why is x (e.g. "manage collaborators") a project-wide preference while y (e.g. "manage payments") is site-wide?

Not really?

> Not to mention the fact that these preferences definitely shouldn't be in the dashboard IMO.

You probably want to be discussing this in https://github.com/dobtco/screendoor-v2/issues/1330.

**Comment by aviv** [comment]
OK gotcha. Will make a note in that thread.
