### ISSUE TITLE
void reference to default project templates 

### ISSUE THREAD

**Issue by kariannemah** [dobtco/knowledge_base#152]
For users who have accidentally deleted a default template, [we encourage them](http://help.dobt.co/articles/screendoor/projects/templates.html#exporting-templates) to download and import a copy from our [Project Templates repo](https://github.com/dobtco/screendoor-project-templates).

With @ajb's reorganization of the repo, the defaults are gone. Should we 
a) add the default templates back to the repo or
b) store them in another repo and update the link in [this answer](http://help.dobt.co/articles/screendoor/projects/templates.html#exporting-templates)?

**Comment by ajb** [comment]
So if you delete _all_ of your templates, there's a link to restore them:

![img](http://take.ms/wZBcS)

Maybe we should just expose that link in a less-prominent place, as long as the user has _at least one_ default template that is deleted.

**Comment by ajb** [comment]
Also, this is my bad, I didn't realize the knowledge base had a link to the default templates from GitHub.

**Comment by kariannemah** [comment]
Exposing the link under that condition makes sense to me. I can think of two places for it now. 

I'll open an issue in the Screendoor repo.

**Comment by ajb** [comment]
New behavior:

![img](https://github.com/dobtco/knowledge_base/issues/152)

Assigning @aviv to update the knowledge base accordingly. Thanks again for the repot!

**Comment by kariannemah** [comment]
Sure thing! :smile:
