### ISSUE TITLE
Switch to SASS

### ISSUE THREAD

**Issue by aviv** [dobtco/knowledge_base#158]
cf. #157

**Comment by aviv** [comment]
First hangup: the knowledge base uses the `based` base stylesheet system, which is written in stylus. There aren't any stylus -> sass converters, as far as I can tell. Assuming we should transition away from `based`, but to what?

**Comment by ajb** [comment]
dvl-core is the successor to based.

On Fri, Feb 20, 2015 at 2:11 PM, Aviv Nitsan <notifications@github.com>
wrote:

> First hangup: the knowledge base uses the based base stylesheet system,
> which is written in stylus. There aren't any stylus -> sass converters, as
> far as I can tell. Assuming we should transition away from based, but to
> what?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/issues/158#issuecomment-75300351>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
