### ISSUE TITLE
Cite screendoor template library

### ISSUE THREAD

**Issue by kariannemah** [dobtco/knowledge_base#160]
Seems like a good idea to mention [our template library](https://github.com/dobtco/screendoor-project-templates) on the [project templates page](http://help.dobt.co/articles/screendoor/projects/templates.html). We could include a couple sections, for starters:
* Browse templates
* Contribute a template

**Comment by ajb** [comment]
Likewise, we should consider adding a tooltip on the "project templates"
settings inside of Screendoor.

On Fri, Feb 20, 2015 at 7:16 PM, Kari Mah <notifications@github.com> wrote:

> Seems like a good idea to mention our template library
> <https://github.com/dobtco/screendoor-project-templates> on the project
> templates page
> <http://help.dobt.co/articles/screendoor/projects/templates.html>. We
> could include a couple sections, for starters:
>
>    - Browse templates
>    - Contribute a template
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/issues/160>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by kariannemah** [comment]
If you're talking adding a tooltip here: http://take.ms/ituz4, it seems like an awkward place for it. Maybe we can place a "Preview additional templates from our library" link under the list of existing templates and above the "Restore default templates" link (when it's visible).

**Comment by ajb** [comment]
Yeah, sorry, I don't know why I said "tooltip". What you said is perfect.
