### ISSUE TITLE
Clarify identification fields

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/knowledge_base#183]
Seems like we could stand to clarify the "identification level" a bit. Maybe a separate page might make sense. (Something like "Collecting personal information"?)

- Explain why Screendoor needs names and email addresses (sending messages, identifying responses, confirmation emails, etc.)
- Explain why you might want to make responses anonymous
- Explain why we need names + emails for forms with payments or e-sig
- Show how to override name and email fields, and when you might want to do so
- Explain how "blind fields" offer greater privacy for respondents / less bias for reviewers while still providing the benefits of collecting personal info

**Comment by ajb** [comment]
:+1: :+1: :+1:

**Comment by aviv** [comment]
This is great, thanks for the brainstorm. This could definitely use some in-depth explanation.
