### ISSUE TITLE
Make new "response selection" UI clearer

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#201]
cf https://app.frontapp.com/api/1/noauth/open_in_front/L2luYm94ZXMvc2hhcmVkL3VuaWZpZWQvb3Blbi8yMTYyODQzNA==

**Comment by aviv** [comment]
Not sure exactly what this would consist of. Maybe something like this?

![](http://take.ms/NnDDW)

The original confusion seems to have come from the *change* we made to the UI, i.e. moving the "select all responses" functionality from the modal to the special checkbox, which means that maybe there's nothing actually wrong with the current UI as it is.

**Comment by aviv** [comment]
Wait, why is this in the KB repo? From the issue name it seems like you're asking about the actual UI, but maybe this is just about the "exporting responses" KB article (that needs to be updated)?

**Comment by ajb** [comment]
Yeah sorry, it's about the exporting responses article and possibly others? I didn't look closely at the articles we have when I filed this. Maybe there should be something in https://github.com/dobtco/knowledge_base/blob/master/contents/articles/screendoor/responses/sorting_and_filtering_responses.md? I dunno.
