### ISSUE TITLE
Add caveat about ridiculous conditional scenarios in rules section

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#205]
At a certain point, you might want to just split your project into two projects.

https://dobt.slack.com/archives/support/p1432249972000225

**Comment by aviv** [comment]
I.e. if you're using rules to divide up your project into two totally separate sections, they should probably just be different projects, yes? Would go here: http://help.dobt.co/articles/screendoor/response_form/building_your_form.html#adding-rules

**Comment by ajb** [comment]
Sounds good. I would try to keep it general, something like:

> You should strive to keep your forms simple. If you find yourself
creating complex conditional scenarios, or creating forms with dozens of
pages, you might consider breaking your form up into separate forms.

On Thu, Jul 23, 2015 at 6:07 PM, Aviv Nitsan <notifications@github.com>
wrote:

> I.e. if you're using rules to divide up your project into two totally
> separate sections, they should probably just be different projects, yes?
> Would go here:
> http://help.dobt.co/articles/screendoor/response_form/building_your_form.html#adding-rules
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/issues/205#issuecomment-124251649>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
