### ISSUE TITLE
Add notes to plan-restricted features

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#206]

**Comment by aviv** [comment]
Parsing this out: this would mean adding notes explaining plan limits to the "creating a project" and "adding collaborators" sections, probably linking to [the plan limits page](http://help.dobt.co/articles/screendoor/plans_and_billing/limitations.html), yes?

**Comment by ajb** [comment]
No, I don't think so. I think this refers to the features that we recently limited:

![img](http://take.ms/x8fgY)
