### ISSUE TITLE
update screenshots for new dvl-core

### ISSUE THREAD

**Issue by aviv** [dobtco/knowledge_base#215]
cf. https://github.com/dobtco/screendoor-v2/pull/2153

@ajb shall I retake all of our screenshots?

**Comment by ajb** [comment]
Yes, I think that's a good call. It can also be a chance for more QA :sparkles:

**Comment by aviv** [comment]
Sounds good. Will be working on this through tomorrow then, and make sure to get it merged by Wednesday.
