### ISSUE TITLE
Document all keyboard shortcuts

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/knowledge_base#227]
We should have a support page listing all keyboard shortcuts on Screendoor.

**Comment by ajb** [comment]
Not sure why we would need this, if on each page in Screendoor, you can simply press `?` and see the modal?

**Comment by jrubenoff** [comment]
Yeah, but we don't even document that.

Also, it's good for us on the product team, and the documentation helps us stay consistent. (For example, making sure `J` and `K` is always used for navigating to the previous / next item on the page.)

**Comment by ajb** [comment]
I'm :+1: for adding a page about keyboard shortcuts, and documenting how you can press `?` to see the shortcuts available on a page.

However, I'd prefer not to document each shortcut on the knowledge base -- just seems like a lot of work to maintain.
