### ISSUE TITLE
explain how to add users to your organization

### ISSUE THREAD

**Issue by jkgoldst** [dobtco/knowledge_base#228]
to avoid this...

![image](https://cloud.githubusercontent.com/assets/6295313/9535721/5de46e24-4cd9-11e5-93bd-df5c510b47bf.png)

cc: @jrubenoff @kariannemah

**Comment by kariannemah** [comment]
:+1: 

[The current KB page on adding a new user](http://help.dobt.co/articles/dashboard/accounts/managing_users.html) will be updated to [this](https://github.com/dobtco/knowledge_base/blob/2dd4bbdff1a6c99a3ab895124ecb1441ff8c28d6/contents/articles/your_account/accounts/managing_users.md) once we merge [the `revamp` branch] (https://github.com/dobtco/knowledge_base/tree/revamp).
