### ISSUE TITLE
Update advanced search screenshots for "More..." button

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#243]

**Comment by ajb** [comment]
I think just updating this screenshot will be OK:  https://github.com/dobtco/knowledge_base/blob/master/contents/articles/screendoor/images/search_responses_2.png

I was about to do it myself, but I don't actually know what software y'all are using to do the masking effect!

**Comment by kariannemah** [comment]
In Preview.app, Tools > Annotate > Mask
