### ISSUE TITLE
Add FAQ / clarity on timezones

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#263]
https://app.frontapp.com/open/L2luYm94ZXMvc2hhcmVkL3VuaWZpZWQvb3Blbi83NTI1NjQyNA==

**Comment by kariannemah** [comment]
I read through the support convo, but I'm still a bit confused: why is the current FAQ not sufficiently clear? 

![screen shot 2016-02-23 at 9 07 05 am](https://cloud.githubusercontent.com/assets/970325/13259578/d9c5fa4c-da0c-11e5-9b89-9e90daef953d.png)

**Comment by ajb** [comment]
Nah, I just didn't realize that was in there already :D

**Comment by kariannemah** [comment]
kk :+1:
