### ISSUE TITLE
Standardize language for "project wizard" vs. "tabs in the wizard menu", etc.

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#275]
Worth noting: we no longer call it a "wizard" inside of Screendoor.

**Comment by ajb** [comment]
cc @jrubenoff -- maybe you have a preference here?

**Comment by jrubenoff** [comment]
Did we ever call it a wizard in the UI itself? We had an “edit” link that
led to a “progress” checklist...

I’m fine with saying “wizard” for now.

**Comment by ajb** [comment]
OK -- I thought you had a preference to not call it that. No prob.

**Comment by jrubenoff** [comment]
Not in the product, but in help docs I’m not sure what would be more
descriptive.
