### ISSUE TITLE
Add a note about the "Only allow one response per account" setting

### ISSUE THREAD

**Issue by kariannemah** [dobtco/knowledge_base#278]
See https://github.com/dobtco/screendoor-v2/pull/3457#issuecomment-202602995

**Comment by ajb** [comment]
Maybe this should be a F.A.Q? Something like:

> **How do I prevent respondents from submitting more than one response?**
> 
> In order to limit a respondent to only one response, you must first change your form to require registration. After doing so, you can then check the "only allow one response per respondent" checkbox.

(Ignore the copy -- I'm just illustrating the gist of the content.)

**Comment by ajb** [comment]
This has been deployed.
