### ISSUE TITLE
Update for respondent auth

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#300]
cf https://github.com/dobtco/screendoor-v2/pull/3704

I don't actually think that much needs to change, since we don't cover respondent view in the knowledge base.

- No more "require respondents to have an account"
- We now show the response permalink on the drafts page
- What else?

**Comment by kariannemah** [comment]
I think you covered it. So that means we only need to update screenshots for "Collecting names and emails" and "Providing support to respondents."
