### ISSUE TITLE
Evaluation fields "Only show to... [team]"

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#310]
Couldn't find this in here.

**Comment by kariannemah** [comment]
Would it help to add a link to http://help.dobt.co/articles/screendoor/collaboration/teams.html#assigning-work-to-teams on http://help.dobt.co/articles/screendoor/evaluation/setting_up_ratings.html? I could update [the screenshot](http://help.dobt.co/articles/screendoor/images/teams_4.png), too.

**Comment by ajb** [comment]
Sounds good!

On Sun, Jul 10, 2016 at 9:17 PM, Kari Mah <notifications@github.com> wrote:

> Would it help to add a link to
> http://help.dobt.co/articles/screendoor/collaboration/teams.html#assigning-work-to-teams
> on
> http://help.dobt.co/articles/screendoor/evaluation/setting_up_ratings.html?
> I could update the screenshot
> <http://help.dobt.co/articles/screendoor/images/teams_4.png>, too.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dobtco/knowledge_base/issues/310#issuecomment-231638998>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABNiLbLK2bsSX-pinvkS2SnEGmMgbGzFks5qUcPwgaJpZM4JCaOM>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
