### ISSUE TITLE
Update for new default admin notification level

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#312]
Deployed here: https://github.com/dobtco/screendoor-v2/pull/3854

http://help.dobt.co/articles/screendoor/responses/notifications.html#project-wide-notifications

We could probably stand to add a little more info on this page? 

Also, cf https://app.frontapp.com/open/L2luYm94ZXMvc2hhcmVkL3N1cHBvcnQvYWxsLzEyNjAwMzc3MA%3D%3D

**Comment by kariannemah** [comment]
Closed with #314.
