### ISSUE TITLE
Search index doesn't match well enough

### ISSUE THREAD

**Issue by ajb** [dobtco/knowledge_base#92]
"Email confirmations" doesn't match anything, because the article is titled "Confirmation emails"

**Comment by ajb** [comment]
Let's do it.

**Comment by aviv** [comment]
Maybe https://github.com/fergiemcdowall/search-index is a better option than the current `query-engine`, or maybe there are some other possibilities? If we use a different query/search library with support for weighting fields (titles > body text) and a better interface, it seems like it'll be easier to upgrade the search.

**Comment by ajb** [comment]
Sure, give it a try. I would write some simple tests if I were you. It's
probably easiest to test the requests to the search endpoint. (You'll want
to use fixture data.)

On Thu, Feb 26, 2015 at 5:44 PM, Aviv Nitsan <notifications@github.com>
wrote:

> Maybe https://github.com/fergiemcdowall/search-index is a better option
> than the current query-engine, or maybe there are some other
> possibilities? If we use a different query/search library with support for
> weighting fields (titles > body text) and a better interface, it seems like
> it'll be easier to upgrade the search.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/issues/92#issuecomment-76291499>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by aviv** [comment]
`search-index` takes an incredibly long time to make its index, and it's pretty buggy as well. :-1:

researching other options, but it's kind of surprising to me that there aren't more/any decent search libraries.

**Comment by ajb** [comment]
If the only thing we're looking to do is weight title > body, can't we just write a little bit of code to do that with the current search server?

**Comment by aviv** [comment]
Yeah sure, but I was hoping we'd be able to find a better search lib that might do "fuzzy" search and some other things. But doesn't seem like there's much available, so I'll try that out.

**Comment by ajb** [comment]
For fuzzy search, you'll probably need a "real" database -- Solr, Lucene, Elastisearch, etc.... and these aren't fun, and are probably way overkill for this project.

There are also SaaS services like https://www.algolia.com/ and https://www.searchify.com/plans/, but they're way overkill for this project... also, def don't want spend mony.

**Comment by aviv** [comment]
ty! i'll focus on just added weight for now.

**Comment by aviv** [comment]
Moving to PR
